# -*- coding: utf-8 -*-
"""Y.KANIYAMUDHAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMSlwVXbIGzEUcdry-ACGId_5LiXfiBG

**1ST TASK LINEAR REGRESSSION**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url = "http://bit.ly/w-data"
dataset = pd.read_csv(url)
print("Data imported successfully")
dataset.head(10)

dataset.plot(x='Hours',y='Scores',style='*')
plt.title('houres vs scores')
plt.xlabel('hours')
plt.ylabel('scores')
plt.show()

x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,1].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.linear_model import LinearRegression

a = LinearRegression()
a.fit(x_train, y_train)

print("Training complete.")

b=a.coef_*x + a.intercept_
plt.scatter(x,y)
plt.plot(x,b)
plt.plot

x_test
y_pred=a.predict(x_test)

c=pd.DataFrame({'Actual':y_test,'predict':y_pred})
c

hours = np.array(9.25).reshape(-1, 1)
own_pred = a.predict(hours)
print("No of Hours = {}".format(hours[0, 0]))
print("Predicted Score = {}".format(own_pred[0]))

from sklearn import metrics
print('Mean Absolute Error:',
      metrics.mean_absolute_error(y_test, y_pred))

"""**overall code**"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url = "http://bit.ly/w-data"
dataset = pd.read_csv(url)
print("Data imported successfully")
dataset.head(10)
dataset.plot(x='Hours',y='Scores',style='*')
plt.title('houres vs scores')
plt.xlabel('hours')
plt.ylabel('scores')
plt.show()
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,1].values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
from sklearn.linear_model import LinearRegression
a = LinearRegression()
a.fit(x_train, y_train)
print("Training complete.")
b=a.coef_*x + a.intercept_
plt.scatter(x,y)
plt.plot(x,b)
plt.plot
x_test
y_pred=a.predict(x_test)
hours = np.array(9.25).reshape(-1, 1)
own_pred = a.predict(hours)
print("No of Hours = {}".format(hours[0, 0]))
print("Predicted Score = {}".format(own_pred[0]))
from sklearn import metrics
print('Mean Absolute Error:',
      metrics.mean_absolute_error(y_test, y_pred))

"""Predicted by: KANIYAMUDHAN Y

"""